some small changes
yourlostitems/yourlostitems.github.io pull request #5
Opened 2024-06-25 17:24 UTC by Yeetface513

Hope you accept these qol and phrasing fixes

2024-06-26 12:30 UTC, Yeetface513 commented
also removed the grabify link from @uimaxbai @rocketman12435 please merge this

2024-06-26 12:42 UTC, Yeetface513 commented
do it

2024-06-26 12:50 UTC, Yeetface513 reviewed
an urgent fix

2024-06-26 12:50 UTC, Yeetface513 commented
must be done with haste

2024-06-26 14:59 UTC, uimaxbai commented
I did not add any of such link. The commit history clearly states that @rocketman12435 did it.

2024-06-26 15:00 UTC, uimaxbai commented
Also there is inappropriate language in the SECURITY.md file, I would recommend not merging this.

2024-06-26 15:01 UTC, uimaxbai commented
nvm its been changed

2024-06-26 15:02 UTC, uimaxbai commented
It also puts my name in strikethrough in the index.html file (very inappropriate, do not accept).

2024-06-26 15:03 UTC, uimaxbai commented
I did not send any link of such, the commit history clearly states that @rocketman12435 placed it in.

2024-06-27 16:54 UTC, thisiscoding1234 requested changes
Please make a change to the index to remove the strikethrough on @uimaxbai's name. Otherwise, it LGTM.

2024-06-27 16:54 UTC, thisiscoding1234 commented on index.html
> +      <p>Main contributors: @werdl, @Neodel, @2010person, @Yeetface513 and <s>@uimaxbai</s> (all on GitHub)</p>
The strikethrough is entirely inappropriate.

2024-06-27 16:54 UTC, thisiscoding1234 commented on 404.html
This looks fine and adds information

2024-06-27 16:54 UTC, thisiscoding1234 commented on README.md
This looks good.

2024-06-27 16:54 UTC, thisiscoding1234 commented on SECURITY.md
This also LGTM.

2024-06-27 16:54 UTC, thisiscoding1234 commented on index.html
> +        <em><b>Have you lost an item?</b></em>
This re-wording is better.

2024-06-27 16:54 UTC, thisiscoding1234 commented on index.html
> +      <p>Main contributors: @werdl, @Neodel, @2010person, @Yeetface513 and <s>@uimaxbai</s> (all on GitHub)</p>
Please remove.

2024-06-27 16:54 UTC, thisiscoding1234 commented on login/index.html
Looks fine.

2024-06-28 13:48 UTC, rocketman12435 commented
> I did not place any link of such, the commit history clearly states that @rocketman12435 placed it in.

Actually Max I didn't change anything, I just added all the files that were in the previous repo to a new repo

2024-06-28 13:49 UTC, rocketman12435 commented
Anything you have put on the files, be it helpful or not, has been put into the repo, so you must tell me where it is to remove it

2024-06-28 16:03 UTC, Yeetface513 commented
it's on the login page its the long link I removed (its a grabify link click it to find out)

2024-09-10 13:46 UTC, merged